version: '3'
services:
    mysql:
        image: mysql:5.7
        volumes:
        - ./base/volumenes/mysql:/var/lib/mysql
        restart: always
        ports:
            - "3306:3306"
#        expose:
#      # Opens port 3306 on the container
#            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: banco
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            #MYSQL_ROOT_HOST: database

    nginx:
        image: nginx:alpine
        environment:
            - ALLOW_OVERRIDE=true
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        command: [nginx-debug, '-g', 'daemon off;']
        links:
            - consignacion
            - consulta
            - retiro
            - log
            - mysql
        restart: "unless-stopped"
        ports:
            - "8080:8080"
        
    consignacion:
        environment:
            - ALLOW_OVERRIDE=true
        build: ./consignacion

    consulta:
        build: ./consulta

    retiro:
        build: ./retiro

    log:
        build: ./log

    php_web:
        image: php:7-apache
        volumes:
        # Montamos nuestra web desde fuera en el directorio web del contenedor
            - ./web/:/var/www/html
        expose:
            - 80
        ports:
            - 80:80
        links: 
            - mysql